from metricstics.code.data_processor import DataProcessor

data_processor = DataProcessor()
data_processor.read_data("input_files/list.txt")

# data_processor.generate_random_data()
mean_value = data_processor.get_mean()
median_value = data_processor.get_median()
mode_value = data_processor.get_mode()
min_value = data_processor.get_min_value()
max_value = data_processor.get_max_value()
std_deviation = data_processor.get_standard_deviation()
mean_abs_dev = data_processor.get_mean_absolute_deviation()
print("Mean:", mean_value)
print("Median: ", median_value)
print("Mode: ", mode_value)
print("min_value: ", min_value)
print("max_value: ", max_value)
print("std_deviation: ", std_deviation)
print("mad :", mean_abs_dev)
